# H2 Database Configuration
# MODE=MySQL 兼容 MySQL 语法
# 使用文件数据库模式，将SQL文件放在classpath根目录
jdbc.driver=org.h2.Driver
jdbc.url=jdbc:h2:file:./data/db_test;DB_CLOSE_DELAY=-1;MODE=MySQL
jdbc.username=sa
jdbc.password=